<script type="text/javascript">
	var $j = jQuery.noConflict();
	$j(document).ready(function(){
		$j('#kamtech_scroller_slider').cycle({
			fx: 'fade',
			speed: 'fast',
			timeout: 3000,
			next: '#next_review',
			prev: '#prev_review'
		});
		$j('#kamtech_reviews_scrollbar').tinyscrollbar();	
	}); 
</script>
<?php $reviews = $this->getReviews(); ?>

<?php if(count($reviews)) : ?>
<?php if($this->getViewMode() == 'slider'):?>
<div class="kamtech-block">
	<div class="kamtech-block-title">
    	<strong><span><a href="<?php echo $this->getUrl('reviews');?>" title="<?php echo $this->__('Recent Reviews'); ?>"><?php echo $this->__('Recent Reviews'); ?></a></span></strong>
    </div>
    <div id="kamtech_scroller_slider" class="kamtech-block-content">
    	<?php $i=0;foreach ($reviews->getData() as $review): ?>
        	<?php $product = Mage::getModel('catalog/product')->load($review['entity_pk_value']);?>
            <?php if ($i++%2==0): ?>
        	<div class="kamtech_scroller_item">
            <?php endif; ?>
            	<div class="kamtech_scroller_item">
                	<div class="kamtech_scroller_item_pimage">
                    	<a href="<?php echo $product->getProductUrl();?>" title="<?php echo $product->getName(); ?>"><img src="<?php echo Mage::helper('catalog/image')->init($product, 'image')->resize(80,80)?>" alt="<?php echo $product->getName(); ?>"  /></a>
                    </div>
                    <div class="kamtech_scroller_item_info">
                    	<div class="kamtech_scroller_item_pname">
                        	<a href="<?php echo $product->getProductUrl();?>" title="<?php echo $product->getName(); ?>"><?php echo $product->getName(); ?></a>
                        </div>
                        <div>
                        	<div class="kamtech_rating-box">
                            	<div class="kamtech_rating" style="width:<?php echo $this->getRatingvote($product->getId());?>%"></div>
                            </div>
                        </div>
                    </div>
                    <div class="kamtech_review_item_clear"></div>
                    <div>
                    	<div class="kamtech_scroller_item_title"><?php echo $review['title'];?></div>
                        <div><?php echo $review['detail'];?></div>
                        <div class="kamtech_scroller_item_nickname"><?php echo $review['nickname']; ?></div>
                    </div>
                </div>
            <?php if ($i%2==0): ?>
            </div>
            <?php elseif($this->getCount() == $i): ?>
            </div>
            <?php endif; ?>
        <?php endforeach;?>
    </div>
    <div class="kamtech-block-title">
    	<strong class="kamtech-block-title-bottom" style="float:left;">
        	<a id="prev_review" href="#">Previous</a>
            |
            <a id="next_review" href="#">Next</a>
        </strong>
        <strong class="kamtech-block-title-bottom" style="float:right;">
        	<a href="<?php echo $this->getUrl('reviews');?>"><?php echo $this->__('View All'); ?></a>
        </strong>
    </div>
</div>
<div class="kamtech_review_item_clear" style="width:100%;"></div>
<?php elseif($this->getViewMode() == 'list'):?>
<div class="kamtech-block">
	<div class="kamtech-block-title">
    	<strong><span><a href="<?php echo $this->getUrl('reviews');?>" title="<?php echo $this->__('Recent Reviews'); ?>"><?php echo $this->__('Recent Reviews'); ?></a></span></strong>
    </div>
    <div id="kamtech_scroller_list" class="kamtech-block-content">
    	<?php foreach ($reviews->getData() as $review): ?>
        	<?php $product = Mage::getModel('catalog/product')->load($review['entity_pk_value']);?>
        	<div class="kamtech_scroller_item">
            	<div class="kamtech_list_item">
                	<div class="kamtech_scroller_item_pimage">
                    	<a href="<?php echo $product->getProductUrl();?>" title="<?php echo $product->getName(); ?>"><img src="<?php echo Mage::helper('catalog/image')->init($product, 'image')->resize(80,80)?>" alt="<?php echo $product->getName(); ?>"  /></a>
                    </div>
                    <div class="kamtech_scroller_item_info">
                    	<div class="kamtech_scroller_item_pname">
                        	<a href="<?php echo $product->getProductUrl();?>" title="<?php echo $product->getName(); ?>"><?php echo $product->getName(); ?></a>
                        </div>
                        <div>
                        	<div class="kamtech_rating-box">
                            	<div class="kamtech_rating" style="width:<?php echo $this->getRatingvote($product->getId());?>%"></div>
                            </div>
                        </div>
                    </div>
                    <div class="kamtech_review_item_clear"></div>
                    <div>
                    	<div class="kamtech_scroller_item_title"><?php echo $review['title'];?></div>
                        <div><?php echo $review['detail'];?></div>
                        <div class="kamtech_scroller_item_nickname"><?php echo $review['nickname']; ?></div>
                    </div>
                </div>
            </div>
        <?php endforeach;?>
        <div class="kamtech-block-list-title">
            <strong class="kamtech-block-list-title-bottom" style="float:right;">
                <a href="<?php echo $this->getUrl('reviews');?>"><?php echo $this->__('View All'); ?></a>
            </strong>
    	</div>
    </div>
</div>
<div class="kamtech_review_item_clear" style="width:100%;"></div>
<?php elseif($this->getViewMode() == 'scroller'):?>
<div class="kamtech-block">
	<div class="kamtech-block-title">
    	<strong><span><a href="<?php echo $this->getUrl('reviews');?>" title="<?php echo $this->__('Recent Reviews'); ?>"><?php echo $this->__('Recent Reviews'); ?></a></span></strong>
    </div>
    <div id="kamtech_reviews_scrollbar" class="kamtech-block-content">
    	<div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
        <div class="viewport">
			 <div class="overview">
    	<?php foreach ($reviews->getData() as $review): ?>
        	<?php $product = Mage::getModel('catalog/product')->load($review['entity_pk_value']);?>
        	<div class="kamtech_scroller_scrollitem">
            	<div class="kamtech_scroller_item">
                	<div class="kamtech_scroller_item_pimage">
                    	<a href="<?php echo $product->getProductUrl();?>" title="<?php echo $product->getName(); ?>"><img src="<?php echo Mage::helper('catalog/image')->init($product, 'image')->resize(80,80)?>" alt="<?php echo $product->getName(); ?>"  /></a>
                    </div>
                    <div class="kamtech_scroller_item_info">
                    	<div class="kamtech_scroller_item_pname">
                        	<a href="<?php echo $product->getProductUrl();?>" title="<?php echo $product->getName(); ?>"><?php echo $product->getName(); ?></a>
                        </div>
                        <div>
                        	<div class="kamtech_rating-box">
                            	<div class="kamtech_rating" style="width:<?php echo $this->getRatingvote($product->getId());?>%"></div>
                            </div>
                        </div>
                    </div>
                    <div class="kamtech_review_item_clear"></div>
                    <div>
                    	<div class="kamtech_scroller_item_title"><?php echo $review['title'];?></div>
                        <div><?php echo $review['detail'];?></div>
                        <div class="kamtech_scroller_item_nickname"><?php echo $review['nickname']; ?></div>
                    </div>
                </div>
            </div>
        <?php endforeach;?>
        </div>
        </div>
    </div>
    <div class="kamtech-block-title">
        <strong class="kamtech-block-title-bottom" style="float:right;">
        	<a href="<?php echo $this->getUrl('reviews');?>"><?php echo $this->__('View All'); ?></a>
        </strong>
    </div>
</div>
<div class="kamtech_review_item_clear" style="width:100%;"></div>
<?php endif;?>
<?php endif;?>


